-- Core data is accessed through server-side routes using the service role key.
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.blacklist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  transaction_ref TEXT NOT NULL UNIQUE,
  sender_name TEXT,
  sender_bank TEXT,
  receiver_name TEXT,
  transaction_date TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'verified',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blacklist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.settings, public.blacklist, public.donations TO service_role;

-- OBS may receive alerts with the anon key, but anon clients cannot send them.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'realtime'
      AND tablename = 'messages'
      AND policyname = 'anon_receive_donation_alerts'
  ) THEN
    CREATE POLICY anon_receive_donation_alerts
      ON realtime.messages
      FOR SELECT TO anon
      USING (realtime.topic() = 'donation-alerts' AND realtime.messages.extension = 'broadcast');
  END IF;
END
$$;
